### ISSUE TITLE
setutup password file is created in the wrong location.

### ISSUE THREAD

**Issue by wdl1908** [jnbt/docker-postfixadmin#1]
When the system creates the ___setup_password.php file it's not picked up by the config.local.php

It should not be created in /config/ but in /config/custom/

Or the config.local.php should be adapted to test if the file exists and then import it from the localtion include /config/___setup_password.php

**Comment by jnbt** [comment]
Thanks for the feedback. This was clearly a mistake. I've corrected the issue and also included the fix in the upcoming "postfixadmin 3.0" release
